title: BT3 Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: https://bt3825.github.io/ :slug

social:
  twitter: _BT3
  github: BT3825

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 4210
google_analytics: UA-274215788-1
